{% set name = "dagster_spark" %}
{% set version = "0.6.7.post0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name|replace('_', '-') }}/{{ name|replace('_', '-') }}-{{ version }}.tar.gz"
  sha256: cfa44e4e299e3d06bd8a34900f304c32c5be50600e818e5d373b00b8590dcfb6

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - dagster {{ version }}.*

test:
  imports:
    - dagster_spark

about:
  home: "https://github.com/dagster-io/dagster/tree/master/python_modules/libraries/dagster-spark"
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: "Package for Spark Dagster framework components."

extra:
  recipe-maintainers:
    - conda-forge/dagster
